# Generated by Django 4.0.6 on 2022-07-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=50)),
                ('away_team', models.CharField(max_length=50)),
                ('ftr', models.CharField(max_length=1)),
                ('country', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('fthg', models.IntegerField()),
                ('ftag', models.IntegerField()),
                ('hthg', models.IntegerField(default=0)),
                ('htag', models.IntegerField(default=0)),
            ],
        ),
    ]
